export const CREATURE_LIST_REQUEST = "CREATURE_LIST_REQUEST"
export const CREATURE_LIST_SUCCESS = "CREATURE_LIST_SUCCESS"
export const CREATURE_LIST_FAIL = "CREATURE_LIST_FAIL"

export const CREATURE_DETAILS_REQUEST = "CREATURE_DETAILS_REQUEST"
export const CREATURE_DETAILS_SUCCESS = "CREATURE_DETAILS_SUCCESS"
export const CREATURE_DETAILS_FAIL = "CREATURE_DETAILS_FAIL"
