export const CREATURE_LIST_REQUEST = "CREATURE_LIST_REQUEST"
export const CREATURE_LIST_SUCCESS = "CREATURE_LIST_SUCCESS"
export const CREATURE_LIST_FAIL = "CREATURE_LIST_FAIL"

export const CREATURE_DETAILS_REQUEST = "CREATURE_DETAILS_REQUEST"
export const CREATURE_DETAILS_SUCCESS = "CREATURE_DETAILS_SUCCESS"
export const CREATURE_DETAILS_FAIL = "CREATURE_DETAILS_FAIL"

export const CREATURE_DELETE_REQUEST = "CREATURE_DELETE_REQUEST"
export const CREATURE_DELETE_SUCCESS = "CREATURE_DELETE_SUCCESS"
export const CREATURE_DELETE_FAIL = "CREATURE_DELETE_FAIL"

export const CREATURE_CREATE_REQUEST = "CREATURE_CREATE_REQUEST"
export const CREATURE_CREATE_SUCCESS = "CREATURE_CREATE_SUCCESS"
export const CREATURE_CREATE_FAIL = "CREATURE_CREATE_FAIL"
export const CREATURE_CREATE_RESET = "CREATURE_CREATE_RESET"

export const CREATURE_UPDATE_REQUEST = "CREATURE_UPDATE_REQUEST"
export const CREATURE_UPDATE_SUCCESS = "CREATURE_UPDATE_SUCCESS"
export const CREATURE_UPDATE_FAIL = "CREATURE_UPDATE_FAIL"
export const CREATURE_UPDATE_RESET = "CREATURE_UPDATE_RESET"
