export const SPELL_LIST_REQUEST = "SPELL_LIST_REQUEST"
export const SPELL_LIST_SUCCESS = "SPELL_LIST_SUCCESS"
export const SPELL_LIST_FAIL = "SPELL_LIST_FAIL"

export const SPELL_DETAILS_REQUEST = "SPELL_DETAILS_REQUEST"
export const SPELL_DETAILS_SUCCESS = "SPELL_DETAILS_SUCCESS"
export const SPELL_DETAILS_FAIL = "SPELL_DETAILS_FAIL"

export const SPELL_DELETE_REQUEST = "SPELL_DELETE_REQUEST"
export const SPELL_DELETE_SUCCESS = "SPELL_DELETE_SUCCESS"
export const SPELL_DELETE_FAIL = "SPELL_DELETE_FAIL"

export const SPELL_CREATE_REQUEST = "SPELL_CREATE_REQUEST"
export const SPELL_CREATE_SUCCESS = "SPELL_CREATE_SUCCESS"
export const SPELL_CREATE_FAIL = "SPELL_CREATE_FAIL"
export const SPELL_CREATE_RESET = "SPELL_CREATE_RESET"

export const SPELL_UPDATE_REQUEST = "SPELL_UPDATE_REQUEST"
export const SPELL_UPDATE_SUCCESS = "SPELL_UPDATE_SUCCESS"
export const SPELL_UPDATE_FAIL = "SPELL_UPDATE_FAIL"
export const SPELL_UPDATE_RESET = "SPELL_UPDATE_RESET"
