export const SPELL_LIST_REQUEST = "SPELL_LIST_REQUEST"
export const SPELL_LIST_SUCCESS = "SPELL_LIST_SUCCESS"
export const SPELL_LIST_FAIL = "SPELL_LIST_FAIL"

export const SPELL_DETAILS_REQUEST = "SPELL_DETAILS_REQUEST"
export const SPELL_DETAILS_SUCCESS = "SPELL_DETAILS_SUCCESS"
export const SPELL_DETAILS_FAIL = "SPELL_DETAILS_FAIL"
