const creatures = [
  {
    _id: "1",
    name: "Бес",
    armorClass: 13,
    aligmentId: "?",
    typeId: "?",
    sizeId: "?",
    dangerousId: "?",
    speed: 20,
    speedFlying: 40,
    speedSwim: 0,
    speedSwim: 0,
    speedClimb: 0,
    sense: "?",
    str: 6,
    dex: 17,
    con: 13,
    int: 11,
    wis: 12,
    cha: 14,
    abilities: ["?"],
    action: ["?"],
    description: "looollololol",
    bookId: "?",
  },
  {
    _id: "2",
    name: "НеБес",
    armorClass: 13,
    aligmentId: "?",
    typeId: "?",
    sizeId: "?",
    dangerousId: "?",
    speed: 20,
    speedFlying: 40,
    speedSwim: 0,
    speedSwim: 0,
    speedClimb: 0,
    sense: "?",
    str: 6,
    dex: 17,
    con: 13,
    int: 11,
    wis: 12,
    cha: 14,
    abilities: ["?"],
    action: ["?"],
    description: "looollololol",
    bookId: "?",
  },
]

export default creatures
